log:
  level: debug
  path: stdout
  access_log:
    enable: true
    httpLogPath: /path/http_access.log

gateway:
  graceTimeOut: 50ns
  listenUDPTimeOut: 10s

  httpReadTimeout: 30s
  httpWriteTimeout: 30s
  httpIdleTimeout: 120s