endpoints:
  - name: tcp-1
    listen_port: 8080
    type: tcp
    routers:
      - type: http
        tls_enabled: false
        priority: 1
        rule: PathPrefix(`/`)
        upstream:
          type: url
          paths:
            - http://192.168.50.102:81
          load_balance: 0