endpoints:
  - name: tcp-1
    listen_port: 8080
    type: tcp
    routers:
      - type: grpc
        tls_enabled: true
        host: www.demo.com
        upstream:
          type: serve
          paths:
            - 127.0.0.1:50051
          load_balance: robin
        tls_config:
          type: 1
          csr_file: demo.com.pem
          key_file: demo.com-key.pem
          client_auth: 0
