endpoints:
  - name: tcp-1
    listen_port: 8080
    type: tcp
    routers:
      - type: http
        tls_enabled: true
        rule: PathPrefix(`/`)
        upstream:
          type: url
          paths:
            - http://192.168.50.102:81
          load_balance: robin
      - type: http
        tls_enabled: true
        host: www.demo.com
        rule: PathPrefix(`/`)
        upstream:
          type: url
          paths:
            - http://192.168.50.102:81
          load_balance: robin
        tls_config:
          type: 1
          csr_file: demo.com.pem
          key_file: demo.com-key.pem
          client_auth: 0