basePath: /api/v1
definitions:
  payload.EndPoint:
    properties:
      id:
        type: integer
      name:
        type: string
      routers:
        items:
          $ref: '#/definitions/payload.Router'
        type: array
      type:
        type: string
    type: object
  payload.MiddleWareInfo:
    properties:
      config:
        type: string
      id:
        type: integer
      name:
        type: string
      type:
        type: string
    type: object
  payload.OauthSuccessData:
    properties:
      id:
        type: integer
      toke:
        type: string
      tokenExpireAt:
        type: string
      userName:
        type: string
    type: object
  payload.RegisterUser:
    properties:
      password:
        type: string
      userName:
        type: string
    required:
    - password
    - userName
    type: object
  payload.Response:
    properties:
      code:
        type: string
      data: {}
      msg:
        type: string
      type:
        description: data msg error
        type: string
    type: object
  payload.Router:
    properties:
      endPointId:
        type: integer
      host:
        type: string
      id:
        type: integer
      middlewares:
        items:
          $ref: '#/definitions/payload.MiddleWareInfo'
        type: array
      priority:
        type: integer
      rule:
        type: string
      tls:
        $ref: '#/definitions/payload.TlsInfo'
      tlsEnable:
        type: integer
      type:
        type: string
      upStream:
        $ref: '#/definitions/payload.UpStreamInfo'
    type: object
  payload.TlsInfo:
    properties:
      clientAuth:
        type: string
      type:
        type: string
    type: object
  payload.UpStreamInfo:
    properties:
      loadBalance:
        type: string
      path:
        type: string
      type:
        type: string
      weights:
        type: string
    type: object
info:
  contact: {}
paths:
  /endpoints/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 新增/修改路由配置（未携带id信息为新增）
      parameters:
      - description: 配置id
        in: formData
        name: id
        type: integer
      - description: 网关配置名称
        in: formData
        name: name
        required: true
        type: string
      - description: 类型
        in: formData
        name: type
        required: true
        type: string
      - description: 路由列表
        in: formData
        name: routers
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/payload.Response'
      summary: 新增/修改路由配置
      tags:
      - endpoints
  /endpoints/delete:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 删除路由配置
      parameters:
      - description: 网关配置的id
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/payload.Response'
      summary: 删除路由配置
      tags:
      - endpoints
  /endpoints/detail:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取路由配置详情
      parameters:
      - description: 网关配置的id
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/payload.Response'
      summary: 获取路由配置详情
      tags:
      - endpoints
  /endpoints/list:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取所有路由配置
      parameters:
      - description: 页码数
        in: query
        name: page_num
        required: true
        type: string
      - default: "20"
        description: 分页尺寸
        in: query
        name: page_size
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.EndPoint'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/payload.Response'
      summary: 获取所有路由配置
      tags:
      - endpoints
  /oauth/login/password:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 账号密码登录
      operationId: OauthLoginPassword
      parameters:
      - description: 用户名
        in: query
        name: user_name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.OauthSuccessData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/payload.Response'
      summary: 账号密码登录
      tags:
      - Oauth
  /register/admin:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 注册管理员用户
      parameters:
      - description: 用户名
        in: query
        name: user_name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.OauthSuccessData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/payload.Response'
      summary: 注册管理员用户
      tags:
      - register
  /register/tenant:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 注册租户
      parameters:
      - description: 用户名
        in: query
        name: user_name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.RegisterUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/payload.Response'
      summary: 注册租户
      tags:
      - register
  /version:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取当前版本
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取当前版本
      tags:
      - system
swagger: "2.0"
